### PR TITLE
feat: Add CANCEL JobCd, ACSUrl, PaReq, MD

### PR DESCRIPTION
**Pull request by Futahei**
- add 'CANCEL' JobCd
- fix lint command (add `--fix` option)
- fix README.md (`npm ci` -> `npm run ci`, because `npm ci` is reserved word from node.js v5.7)

### CODE REVIEW

**Comment by Futahei** [comment]
- add `ACSUrl`, `PaReq`, `MD` to `ExecTranResult`

**Comment by Futahei** [comment]
@linyows

**Comment by linyows** [comment]
@Futahei Thanks. Would you please split each change into separate pull-requests? and Please tell us the reason for each change. Oh, I understand the ci command.

**Comment by Futahei** [comment]
I don't want to split the pull request because it is too complicated.
The reason for each change is explained below.

- add 'CANCEL' JobCd
> ・「2.12.2.1. 決済変更」入力パラメータ「JobCd」に CANCEL を追加
> (from document ver 1.31 (updated 2019/04/15))
- fix lint command (add --fix option)
  - for auto fix
- add .gitignore node_modules & nyc_output
  - ignore node_modules is essential if u use npm
  - nyc_output is temp directory
 - add ACSUrl, PaReq, MD to ExecTranResult
   - these are the parameters you will receive when you use secure payment
   - 348c8ff697537d6d370b74f9c749612c
 - fix ACS toUpper
   - the parameter is uppercase

**Comment by linyows** [comment]
There are some changes that cannot be merged without splitting pull-request. 

- `--fix` argument of eslint should be the argument of npm run: `npm run lint -- --fix`
- Things that you normally don't commit, such as node_modules and .nyc_output, should be ignored in your environment
- Coding style changes need to add rules to linter

For API parameters I will check the documentation.

**Comment by Futahei** [comment]
OK, I'll do it later.

**Pull request closed without merging**
