### PR TITLE
Errors

### PR DESCRIPTION
**Pull request by caub**
I realized it's not so ideal to only have English error messages, some were not well translated

So I took back your intial Japanese error messages https://github.com/pepabo/gmopg/blob/42a59c709e9dbbaee724edd2cd00930a069ba988/src/errors.ts#L30 and the current translations, and it's in src/error-codes.json now

it's a breaking change because `badRequest.errors` is an array of `{ja: string, en: string}` instead of array of string

maybe we could have `badRequest.errors` or `badRequest.errorsJa` and `badRequest.errorsEn`?

@linyows

### CODE REVIEW

**Comment by caub** [comment]
`npm run ci` succeeds for me locally, Idk why it fails in travis

**Comment by linyows** [comment]
@caub I agree that it's not the client's job to translate on their own. I think that it is okay to return what is in the API specification document or return the response as it is.

**Comment by linyows** [comment]
> The error instructions are often generic and not so useful, so I used the error message (in Japanese and English) when the table has it

I think so too. It is strange that returns instructions instead of an error message.

**Comment by caub** [comment]
> @caub I agree that it's not the client's job to translate on their own. I think that it is okay to return what is in the API specification document or return the response as it is.

I was given the Japanese and English messages for 269 error codes (E00000000,E01010001, E01010008, E01010010, E01020001, E01020008, ... 42G990000)
 
and src/error-codes.json has 1713 items, I remember I gogole-translated the remaining ones

What do you think we should do? I know GMOPG operates mostly (only?) in Japan, but as a developer I'm quite happy if I've an error message in English :))

**Comment by linyows** [comment]
> What do you think we should do? I know GMOPG operates mostly (only?) in Japan, but as a developer I'm quite happy if I've an error message in English :))

If so, leave English translations. 👍 However, it is good to put a comment in `src/errors.ts` that it may not be correct because it is a Google Translate.

**Comment by caub** [comment]
Yes, good point, I added a comment

**Comment by linyows** [comment]
> `npm run ci` succeeds for me locally, Idk why it fails in travis

Fixed at #21, so merge master please.

**Comment by linyows** [comment]
Thanks!

**Comment by linyows** [comment]
@caub Why is error-codes defined by JSON instead of TS?

**Comment by caub** [comment]
> @caub Why is error-codes defined by JSON instead of TS?

because it's just data, .json is portable so that seems interesting (it's also more [efficient to use json](https://v8.dev/blog/cost-of-javascript-2019#json) than object literals but that was absolutely not a concern when choosing)

**Comment by linyows** [comment]
I didn't know that object literals would be parsed twice if the data was large. I was not realize in this review. Sorry.

**Pull request merged**
